version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
      - MYSQL_DB=library
      - BUCKET_NAME=your-bucket-name
      - CSV_FILE_NAME=your-file-name.csv
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: library
    ports:
      - "3306:3306"
